apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-manager-client
  namespace: task-manager
spec:
  replicas: 2
  selector:
    matchLabels:
      app: task-manager-client
  template:
    metadata:
      labels:
        app: task-manager-client
    spec:
      containers:
        - name: client
          image: task-manager-client:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 10
